### ISSUE TITLE
Issue with version 0.2.12

### ISSUE THREAD

**Issue by keertijoshi** [angular-ui/ui-router#1565]
After upgrading to 0.2.12 all the routes are failing to load and below is the error I am seeing.

"Error: state.ownParams.$$equals is not a function
transitionTo@http://localhost:3000/angular-ui-router/release/angular-ui-router.js:3041:16
$state.transitionTo@http://localhost:3000/ui-router-extras/release/ct-ui-router-extras.js:136:7
$state.transitionTo@http://localhost:3000/ui-router-extras/release/ct-ui-router-extras.js:874:15
$state.transitionTo@http://localhost:3000/ui-router-extras/release/ct-ui-router-extras.js:1301:17
go@http://localhost:3000/angular-ui-router/release/angular-ui-router.js:2958:70
