### ISSUE TITLE
angular 1.4 breaks ui router

### ISSUE THREAD

**Issue by steambap** [angular-ui/ui-router#2022]
When I update angular to 1.4, I have an error: Uncaught TypeError: b.addPollFn is not a function

**Comment by nateabele** [comment]
Unfortunately, with the information you've given me I have no idea how to help you. Please post a plunkr that demonstrates the issue. Thanks.

**Comment by bumblebeeman** [comment]
I have a rather large UI-Router based app running on 1.4 no problem, have you tried making sure you are on latest version of UI-Router?

**Comment by mikehuebner** [comment]
Not to re-open this but I am having an issue where the states aren't applying the ngAnimate classes. I am still looking into why and about to revert to angular 1.3.15 / 16 to see if that fixes it.

**Comment by mikehuebner** [comment]
http://plnkr.co/edit/WV1JksXCBRl7wG6p00ZS?p=preview

Plunkr creating the issue from a guide I found. I updated it to the latest to see what happens and it broke.
